moai:
  initialized: true
  initialized_at: '2025-12-19T00:00:00Z'
  version: 1.14.5
project:
  name: project001
  mode: personal
  description: ''
  created_at: '2026-02-04 02:14:43'
  template_version: 1.14.5
  optimized: false
